name: Robot Dolar Diario

on:
  schedule:
    # Corre cada hora desde las 15:00 hasta las 18:00 UTC 
    # (9:00 AM a 12:00 PM hora CDMX) de lunes a viernes
    - cron: '0 15,16,17,18 * * 1-5'
  workflow_dispatch:
jobs:
  actualizar-dolar:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar librerías
      run: pip install requests gspread

    - name: Correr el Robot
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        BANXICO_TOKEN: ${{ secrets.TOKEN }}
      run: python robot_dolar.py