name: Robot Dolar Diario

on:
  schedule:
    # Corre todos los días a las 14:00 UTC (8:00 AM hora CDMX)
    - cron: '0 14 * * *'
  workflow_dispatch: # Nos deja correrlo a mano desde la web de GitHub por si acaso

jobs:
  actualizar-dolar:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clonar el repositorio
      uses: actions/checkout@v4

    - name: 🐍 Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: 📦 Instalar librerías necesarias
      run: |
        pip install requests gspread

    - name: 🤖 Correr el Robot
      env:
        # Aquí le prestamos la llave secreta a la computadora de GitHub
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: python robot_dolar.py